/** Full SACE course catalogue used in the application form select. */
export const COURSE_OPTIONS = [
  "Cambridge CAE Preparation",
  "Cambridge CELTA full time",
  "Cambridge CELTA part time",
  "Cambridge FCE Preparation",
  "ETS 1 - English for Tertiary Studies I",
  "ETS 2 - English for Tertiary Studies II",
  "ETS 3 - English for Tertiary Studies III",
  "ETS 4 - English for Tertiary Studies IV",
  "General English Evening Course",
  "General English Standard",
  "General Intensive English",
  "High School Preparation Course",
  "IELTS",
  "IELTS Preparation Day Course",
  "IELTS Preparation Evening Course",
  "PTE Academic Preparation Evening",
  "Part-time General English",
] as const;

export const NATIONALITIES = [
  "Australia",
  "Brazil",
  "Chile",
  "China",
  "Colombia",
  "France",
  "Germany",
  "India",
  "Indonesia",
  "Italy",
  "Japan",
  "Korea, South",
  "Malaysia",
  "Mexico",
  "Mongolia",
  "Nepal",
  "Peru",
  "Philippines",
  "Saudi Arabia",
  "Spain",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Turkey",
  "Vietnam",
  "Other",
] as const;
